### ISSUE TITLE
GDPR + Cookies Plugin Notifications Not Displaying Unless Logged into Admin Panel

### ISSUE THREAD

**Issue by BopkyH** [concrete5-community/gdpr#7]
Hello everyone,

I'm facing an issue with the GDPR + Cookies plugin (version 1.8.3) on my Concrete5 Core 8.5.2 website. I've enabled the notifications for GDPR and cookies, but they are not showing up on the website for regular users. Strangely, the notifications only appear when I'm logged into the admin panel.

Has anyone else experienced this issue? Any suggestions on how to resolve it would be greatly appreciated.

Thank you!

**Comment by hissy** [comment]
Cookie notification in the dashboard is the core feature, not from this package. I think you haven't enabled cookie notification yet.
