### ISSUE TITLE
Concrete CMS v9 ready?

### ISSUE THREAD

**Issue by d4bk** [concrete5-community/gdpr#9]
Hey, i want to use this Plugin. Unfortunately it´s not ready for v9. Could someone tell me if its possible to just increase the Version in controller.php ?

`protected $appVersionRequired = '8.4.4';`

Thanks a lot

**Comment by hissy** [comment]
@d4bk 

I'm working on support version 9, but still I have some minor issues.
You can try the `release/1.9.0` branch; it works almost well, especially the cookie notice function should have no problem.

https://github.com/concrete5-community/gdpr/tree/release/1.9.0

If you find some issues, please report and share us. Thanks.

**Comment by d4bk** [comment]
Hey hissy,

thank you. I've tried it today. But i couldn't get it to work. I´m new to Concrete CMS. Maybe i´ve been missing something...

![grafik](https://github.com/concrete5-community/gdpr/assets/48965629/fc54ad85-c20c-4c7d-aa15-2d125707bbcf)
![grafik](https://github.com/concrete5-community/gdpr/assets/48965629/d9ad50c3-5d83-40c5-a6dd-4e0f7702decb)

Thank You

**Comment by mlocati** [comment]
@d4bk please be sure that the package folder name is exactly `gdpr`

**Comment by d4bk** [comment]
> @d4bk please be sure that the package folder name is exactly `gdpr`

Oh, my fault. :-) Thanks! Now it works.

**Comment by hissy** [comment]
Fixed by #5
